config/routes.rb
Rails.application.routes.draw do
   resources :friends, only: [:show, :index, :create, :new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def show
        @friend = Friend.find(params[:id])
        
    end
    def index
        @friend = Friend.all
    end
    def new
    end

    def create
        render plain: params[:friends]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/index.html.erb
index page

<% @friend.each do |friends|%>
    <%=friends.name%>
    <%=friends.age%>
    <%=friends.email%>
<% end %>

app/views/friends/new.html.erb
<h1>Create a new Friend</h1>
 
<%= form_with scope: :friend, url: friends_path, local: true do |f| %>
  <p> 
    <%= f.label :Name %><br/> 
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :Age %><br/> 
    <%= f.number_field :age %> 
  </p>
  <p> 
    <%= f.label :Email %><br/> 
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/friends/show.html.erb
hello

<%= @friend.name%>
<%= @friend.age%>
<%= @friend.email%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>